#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx listening on port 80


 sudo apt-get update -y -qq && \
        sudo apt-get install nginx -y



# starting nginx service and allow on firewall
sudo service nginx start
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files and back up index files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating a new index file piped into index and restart nginx
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Set up /redirect_me
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart

