#!/bin/bash

# Install Nginx web server
sudo apt-get update
sudo apt-get install nginx -y

# Create a new server block for the redirection
sudo tee /etc/nginx/sites-available/redirect_me << EOF
server {
    listen 80;
    server_name example.com;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Other server configurations
}
EOF

# Create a symbolic link to enable the new server block
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test the Nginx configuration and reload Nginx service
sudo nginx -t && sudo systemctl reload nginx

