#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx listening on port 80

echo -e "Updating and installing $Nginx.\n"
 sudo apt-get update -y -qq && \
	sudo apt-get install nginx -y

echo -e "\nConfiguring Nginx...\n"

# starting nginx service and allow on firewall
sudo service nginx start
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files and back up index files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating a new index file piped into index and restart nginx
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Set up /redirect_me
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Set up a 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

sudo service nginx restart
echo -e "\nConfiguration Completed.\n"
