#!/usr/bin/env bash

# Define the IP addresses of the web servers

WEB_SERVERS=( "web-01" "web-02" )

# Define the command to set the custom HTTP header in Nginx

NGINX_CMD='echo "add_header X-Served-By \$hostname;" | sudo tee -a /etc/nginx/nginx.conf >/dev/null'

# Loop through the web servers and configure Nginx with the custom HTTP header
for SERVER in "${WEB_SERVERS[@]}"
do
    echo "Configuring $SERVER..."
    ssh ubuntu@"$SERVER" "$NGINX_CMD"
    ssh ubuntu@"$SERVER" sudo service nginx restart
done

echo "Done!"

